name: Daily Channel Post
on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Post
        run: |
          curl -s -X POST \
          -d chat_id=@HyperballoidAIArt \
          -d text="Daily update! Try /guide for AI art tips. Щоп’ятниці: український контент! #NFTart" \
          https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
